### ISSUE TITLE
SoomlaStore: Failed to verify transaction receipt

### ISSUE THREAD

**Issue by aozolabo** [soomla/cocos2dx-store#193]
Hi,

I'm using soomla purchase framework with cocos2dx 3.7 to purchase consumable items on iOS.
I don't know when it happened, but recently Soomla Server Side Verification returns the following error.

`[*** ERROR ***] SOOMLA SoomlaStore: Failed to verify transaction receipt for MY_PURCHASE_ITEM. The user will not get what he just bought.`

It was OK before June, but we get this error now.
We used to check receipt verification on Soomla SSV and our server twice.
There are no issue on our server, so we removed soomla ssv now.
Does anyone know what happens?
Thanks.

**Comment by EugeneButusov** [comment]
Hi @aozolabo. As we noticed on forums, fraud protection service was moved at https://iap.vedidev.com (Soomla supporting team since Grow will down). Some days ago we had some adjustments there and redirected verify.soom.la traffic there. Now all should be good. Could you please tell me if this issue is still here?

**Comment by aozolabo** [comment]
@EugeneButusov

**Comment by aozolabo** [comment]
Hi @EugeneButusov.
Thank you and sorry that we just missed your notice.
